package viewFramework;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;



public abstract class JDialog_AddingAccount extends javax.swing.JDialog
{

	private static final long serialVersionUID = 1L;
	public ApplicationFrame parentframe;

	public abstract String getDialogTitle();

	public JDialog_AddingAccount(ApplicationFrame parent)
	{
		super(parent);
		parentframe=parent;

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle(getDialogTitle());
		setModal(true);
		getContentPane().setLayout(null);
		setSize(293,311);
		setVisible(false);

		addRadioButtons();

		JLabel1.setText("Name");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setBounds(12,72,48,24);
		JLabel2.setText("Street");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.black);
		JLabel2.setBounds(12,96,48,24);
		JLabel3.setText("City");
		getContentPane().add(JLabel3);
		JLabel3.setForeground(java.awt.Color.black);
		JLabel3.setBounds(12,120,48,24);
		JLabel4.setText("State");
		getContentPane().add(JLabel4);
		JLabel4.setForeground(java.awt.Color.black);
		JLabel4.setBounds(12,144,48,24);
		JLabel5.setText("Zip");
		getContentPane().add(JLabel5);
		JLabel5.setForeground(java.awt.Color.black);
		JLabel5.setBounds(12,168,48,24);
		JLabel6.setText("Email");
		getContentPane().add(JLabel6);
		JLabel6.setForeground(java.awt.Color.black);
		JLabel6.setBounds(12,192,48,24);

		addAdditionallables();

		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(120,72,156,20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(120,96,156,20);
		getContentPane().add(JTextField_CT);
		JTextField_CT.setBounds(120,120,156,20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(120,144,156,20);
		getContentPane().add(JTextField_STR);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(120,168,156,20);
		getContentPane().add(JTextField_additional1);
		JTextField_additional1.setBounds(120,192,156,20);
		getContentPane().add(JTextField_EM);
		JTextField_EM.setBounds(120,216,156,20);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48,280,84,24);
		JButton_Calcel.setText("Cancel");
		JButton_Calcel.setActionCommand("Cancel");
		getContentPane().add(JButton_Calcel);
		JButton_Calcel.setBounds(156,280,84,24);

		//}}

		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		JButton_Calcel.addActionListener(lSymAction);
		//}}
	}

		int xx=0;
		List<JTextField> fields = new ArrayList<JTextField>();

	private void addAdditionallables() {
		int c =0;

		for(String s : getadditionalLable())
		{
			c++;
			getContentPane().add(getMeAJLable(s, xx+=24));
			if(c>1)
			getContentPane().add(getMeAJTextField(xx-24));
		}

	}

	public JLabel getMeAJLable(String s, int x)
	{
		JLabel label = new JLabel();
		label.setText(s);
		label.setForeground(java.awt.Color.black);
		label.setBounds(12,192+x,96,24);
		return label;
	}

	public JTextField getMeAJTextField(int x)
	{
		JTextField f = new JTextField();
		fields.add(f);
		f.setBounds(120,216+x,156,20);
		return f;
	}

	public List<JTextField> getTextFields(){
		return fields;
	}


	abstract public  List<String> getadditionalLable();

	private void addRadioButtons() {
		for (JRadioButton r: getRadioButtons())
			getContentPane().add(r);

	}


	public abstract List<JRadioButton> getRadioButtons();

	//{{DECLARE_CONTROLS
	JLabel JLabel1 = new JLabel();
	JLabel JLabel2 = new JLabel();
	JLabel JLabel3 = new JLabel();
	JLabel JLabel4 = new JLabel();
	JLabel JLabel5 = new JLabel();
	JLabel JLabel6 = new JLabel();
	JLabel JLabel7 = new JLabel();
	JTextField JTextField_NAME = new JTextField();
	JTextField JTextField_CT = new JTextField();
	JTextField JTextField_ST = new JTextField();
	JTextField JTextField_STR = new JTextField();
	JTextField JTextField_ZIP = new JTextField();
	protected JTextField JTextField_additional1 = new JTextField();
	public JTextField JTextField_EM = new JTextField();
	JRadioButton radioButtonTest = new JRadioButton();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	javax.swing.JButton JButton_Calcel = new javax.swing.JButton();

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
			else if (object == JButton_Calcel)
				JButtonCalcel_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event)
	{
       parentframe.clientName = JTextField_NAME.getText();
       parentframe.street = JTextField_STR.getText();
       parentframe.city = JTextField_CT.getText();
       parentframe.zip = JTextField_ZIP.getText();
       parentframe.state = JTextField_ST.getText();
       parentframe.email = JTextField_EM.getText();

	   parentframe.balance = "0";

       additionalOK_actionPerformed();

       for(JRadioButton radioButton : getRadioButtons())
       {
    	     if (radioButton.isSelected())
    	     {
    	           parentframe.accountType= String.valueOf(radioButton.getText().charAt(0));
    	           parentframe.accountType = "S";
			 }
       }

	   parentframe.newaccount=true;
	   dispose();

	}

	public abstract void additionalOK_actionPerformed();

	void JButtonCalcel_actionPerformed(java.awt.event.ActionEvent event)
	{
		dispose();

	}
}